packages:
  - 'apps/*'
  - 'libs/dashboard/feature/*'
  - 'libs/dashboard-shell/feature/*'
  - 'libs/shared/ui/*'
  - 'libs/dashboard/data/*'
  - 'libs/workflow-engine/feature/*'
  - 'libs/shared/util/*'
  - 'libs/workflow-engine/utils/*'
  - 'libs/shared/data/*'
  - 'libs/workflow-engine/data/*'
  - 'data-unassigned'
  - 'libs/dashboard-shell/*'
  - 'libs/dashboard-shell/utils/*'
