import { SharedUiDrawer } from '@office-automation/shared/ui/drawer';
import { dashboardDataMenuItems } from '@office-automation/dashboard/data/menu';

const userpermission = [
  {
    AccessGroupId: 1,
    SystemEntityId: 12,
    Id: 5473,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 13,
    Id: 5582,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 18,
    Id: 5312,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 19,
    Id: 5336,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 28,
    Id: 5401,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 29,
    Id: 5402,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 30,
    Id: 5403,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 31,
    Id: 5607,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 36,
    Id: 5457,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 39,
    Id: 5698,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 53,
    Id: 5469,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 58,
    Id: 5475,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 60,
    Id: 5480,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 61,
    Id: 5481,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 62,
    Id: 5482,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 68,
    Id: 5483,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 69,
    Id: 5484,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 70,
    Id: 5485,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 71,
    Id: 5486,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 72,
    Id: 5487,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 73,
    Id: 5378,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 74,
    Id: 5314,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 75,
    Id: 5315,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 76,
    Id: 5316,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 77,
    Id: 5317,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 78,
    Id: 5318,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 79,
    Id: 5319,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 80,
    Id: 5321,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 81,
    Id: 5322,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 82,
    Id: 5323,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 83,
    Id: 5324,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 84,
    Id: 5326,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 85,
    Id: 5327,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 86,
    Id: 5328,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 87,
    Id: 5330,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 88,
    Id: 5331,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 89,
    Id: 5332,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 90,
    Id: 5333,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 91,
    Id: 5349,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 92,
    Id: 5350,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 93,
    Id: 5351,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 94,
    Id: 5352,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 95,
    Id: 5355,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 96,
    Id: 5356,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 97,
    Id: 5357,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 98,
    Id: 5358,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 99,
    Id: 5361,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 100,
    Id: 5362,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 101,
    Id: 5363,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 102,
    Id: 5365,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 103,
    Id: 5366,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 104,
    Id: 5367,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 105,
    Id: 5369,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 106,
    Id: 5370,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 107,
    Id: 5371,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 108,
    Id: 5372,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 109,
    Id: 5374,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 110,
    Id: 5375,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 111,
    Id: 5376,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 112,
    Id: 5377,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 113,
    Id: 5380,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 114,
    Id: 5381,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 115,
    Id: 5382,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 116,
    Id: 5383,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 117,
    Id: 5384,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 119,
    Id: 5511,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 120,
    Id: 5512,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 121,
    Id: 5513,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 122,
    Id: 5514,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 123,
    Id: 5515,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 124,
    Id: 5516,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 125,
    Id: 5390,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 126,
    Id: 5391,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 127,
    Id: 5392,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 128,
    Id: 5393,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 129,
    Id: 5394,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 130,
    Id: 5395,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 133,
    Id: 5398,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 134,
    Id: 5399,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 135,
    Id: 5400,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 136,
    Id: 5413,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 137,
    Id: 5414,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 138,
    Id: 5415,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 140,
    Id: 5418,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 141,
    Id: 5419,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 142,
    Id: 5420,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 144,
    Id: 5423,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 145,
    Id: 5424,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 146,
    Id: 5425,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 147,
    Id: 5426,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 148,
    Id: 5427,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 149,
    Id: 5431,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 150,
    Id: 5432,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 151,
    Id: 5433,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 152,
    Id: 5434,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 153,
    Id: 5435,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 154,
    Id: 5493,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 155,
    Id: 5494,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 157,
    Id: 5495,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 158,
    Id: 5496,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 159,
    Id: 5497,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 160,
    Id: 5500,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 162,
    Id: 5471,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 164,
    Id: 5451,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 165,
    Id: 5452,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 166,
    Id: 5453,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 167,
    Id: 5454,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 168,
    Id: 5517,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 169,
    Id: 5396,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 170,
    Id: 5436,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 171,
    Id: 5428,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 172,
    Id: 5459,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 173,
    Id: 5460,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 174,
    Id: 5461,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 175,
    Id: 5462,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 176,
    Id: 5385,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 177,
    Id: 5421,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 178,
    Id: 5416,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 183,
    Id: 5488,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 185,
    Id: 5464,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 186,
    Id: 5465,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 187,
    Id: 5466,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 188,
    Id: 5467,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 189,
    Id: 5468,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 190,
    Id: 5508,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 191,
    Id: 5455,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 193,
    Id: 5456,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 196,
    Id: 5527,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 198,
    Id: 5353,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 201,
    Id: 5659,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 202,
    Id: 5660,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 203,
    Id: 5661,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 204,
    Id: 5662,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 206,
    Id: 5665,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 207,
    Id: 5666,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 208,
    Id: 5667,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 209,
    Id: 5663,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 213,
    Id: 5429,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 233,
    Id: 5529,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 234,
    Id: 5530,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 235,
    Id: 5531,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 236,
    Id: 5532,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 237,
    Id: 5533,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 238,
    Id: 5534,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 239,
    Id: 5535,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 240,
    Id: 5536,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 244,
    Id: 5537,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 246,
    Id: 5518,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 248,
    Id: 5439,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 249,
    Id: 5441,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 250,
    Id: 5442,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 251,
    Id: 5443,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 252,
    Id: 5444,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 253,
    Id: 5445,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 254,
    Id: 5446,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 255,
    Id: 5437,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 256,
    Id: 5334,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 257,
    Id: 5538,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 259,
    Id: 5526,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 267,
    Id: 5386,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 269,
    Id: 5338,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 270,
    Id: 5339,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 271,
    Id: 5340,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 273,
    Id: 5341,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 274,
    Id: 5541,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 277,
    Id: 5544,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 281,
    Id: 5519,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 282,
    Id: 5404,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 283,
    Id: 5406,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 286,
    Id: 5502,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 287,
    Id: 5503,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 288,
    Id: 5504,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 289,
    Id: 5505,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 290,
    Id: 5506,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 291,
    Id: 5507,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 293,
    Id: 5498,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 297,
    Id: 5523,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 298,
    Id: 5547,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 299,
    Id: 5548,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 300,
    Id: 5549,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 301,
    Id: 5550,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 302,
    Id: 5551,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 303,
    Id: 5542,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 304,
    Id: 5545,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 305,
    Id: 5447,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 306,
    Id: 5472,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 307,
    Id: 5521,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 308,
    Id: 5522,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 309,
    Id: 5359,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 321,
    Id: 5343,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 322,
    Id: 5344,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 323,
    Id: 5345,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 324,
    Id: 5346,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 326,
    Id: 5563,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 327,
    Id: 5565,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 328,
    Id: 5566,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 329,
    Id: 5567,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 330,
    Id: 5568,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 347,
    Id: 5636,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 348,
    Id: 5638,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 350,
    Id: 5695,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 352,
    Id: 5639,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 358,
    Id: 5552,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 359,
    Id: 5554,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 360,
    Id: 5575,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 361,
    Id: 5576,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 362,
    Id: 5577,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 363,
    Id: 5578,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 364,
    Id: 5579,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 365,
    Id: 5580,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 366,
    Id: 5558,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 367,
    Id: 5559,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 368,
    Id: 5561,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 369,
    Id: 5562,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 371,
    Id: 5570,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 372,
    Id: 5571,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 373,
    Id: 5572,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 374,
    Id: 5573,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 383,
    Id: 5640,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 385,
    Id: 5641,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 386,
    Id: 5642,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 387,
    Id: 5643,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 388,
    Id: 5644,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 389,
    Id: 5645,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 390,
    Id: 5646,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 392,
    Id: 5647,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 393,
    Id: 5648,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 394,
    Id: 5649,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 395,
    Id: 5650,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 396,
    Id: 5651,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 397,
    Id: 5652,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 398,
    Id: 5653,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 399,
    Id: 5654,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 404,
    Id: 5387,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 408,
    Id: 5489,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 409,
    Id: 5478,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 410,
    Id: 5479,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 411,
    Id: 5655,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 412,
    Id: 5448,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 413,
    Id: 5408,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 414,
    Id: 5409,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 415,
    Id: 5410,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 417,
    Id: 5656,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 419,
    Id: 5490,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 420,
    Id: 5438,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 422,
    Id: 5668,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 423,
    Id: 5670,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 424,
    Id: 5671,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 425,
    Id: 5672,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 426,
    Id: 5673,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 427,
    Id: 5674,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 428,
    Id: 5675,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 429,
    Id: 5676,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 430,
    Id: 5677,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 431,
    Id: 5678,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 432,
    Id: 5679,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 433,
    Id: 5680,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 434,
    Id: 5681,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 435,
    Id: 5682,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 436,
    Id: 5683,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 438,
    Id: 5685,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 439,
    Id: 5597,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 441,
    Id: 5687,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 442,
    Id: 5583,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 443,
    Id: 5584,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 444,
    Id: 5689,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 445,
    Id: 5690,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 447,
    Id: 5696,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 450,
    Id: 5589,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 451,
    Id: 5590,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 452,
    Id: 5585,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 453,
    Id: 5586,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 454,
    Id: 5587,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 455,
    Id: 5599,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 456,
    Id: 5600,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 457,
    Id: 5601,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 458,
    Id: 5594,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 459,
    Id: 5595,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 460,
    Id: 5596,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 461,
    Id: 5686,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 463,
    Id: 5603,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 464,
    Id: 5604,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 465,
    Id: 5605,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 466,
    Id: 5335,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 467,
    Id: 5591,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 468,
    Id: 5592,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 470,
    Id: 5608,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 471,
    Id: 5609,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 472,
    Id: 5610,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 473,
    Id: 5611,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 474,
    Id: 5692,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 475,
    Id: 5693,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 476,
    Id: 5555,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 478,
    Id: 5699,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 479,
    Id: 5700,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 481,
    Id: 5613,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 482,
    Id: 5614,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 483,
    Id: 5615,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 485,
    Id: 5617,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 486,
    Id: 5618,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 487,
    Id: 5619,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 489,
    Id: 5621,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 490,
    Id: 5622,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 491,
    Id: 5623,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 493,
    Id: 5625,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 494,
    Id: 5626,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 495,
    Id: 5627,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 496,
    Id: 5628,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 497,
    Id: 5629,
    IsChecked: true,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 499,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 500,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 502,
    Id: 5631,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 503,
    Id: 5632,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 504,
    Id: 5633,
    IsChecked: true,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 505,
    Id: 5634,
    IsChecked: true,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 507,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 508,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 509,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 510,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 511,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 512,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 513,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 514,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 515,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 516,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 517,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 518,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 519,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 520,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 521,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 522,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 523,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 524,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 525,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 526,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 527,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 528,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 529,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 530,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 531,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 532,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 534,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 535,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 536,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 537,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 538,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 539,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 540,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 541,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 542,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 543,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 544,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 546,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 547,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 548,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 550,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 551,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 552,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 553,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 555,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 556,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 557,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 559,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 560,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 561,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 563,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 564,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 565,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 567,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 568,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 569,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 570,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 571,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 572,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 573,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 574,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 575,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 576,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 577,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 578,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 579,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 0,
    SystemEntityId: 580,
    Id: 0,
    IsChecked: false,
  },
  {
    AccessGroupId: 1,
    SystemEntityId: 581,
    Id: 5635,
    IsChecked: true,
  },
];

type PermissionItem = {
  AccessGroupId: number;
  SystemEntityId: number;
  Id: number;
  IsChecked: boolean;
};

export function DashboardFeatureShell() {
  let dictionaryuserPermission: Record<number, PermissionItem> = {};

  dictionaryuserPermission = userpermission.reduce((acc, item) => {
    acc[item.SystemEntityId] = {
      AccessGroupId: item.AccessGroupId,
      SystemEntityId: item.SystemEntityId,
      Id: item.Id,
      IsChecked: item.IsChecked,
    };
    return acc;
  }, {} as Record<number, PermissionItem>);

  const allowedMenuIds = dashboardDataMenuItems
    .map((item, index) => {
      if (dictionaryuserPermission[item.id]?.IsChecked) {
        return item;
      }
    })
    .filter((item) => item);

  return (
    <div>
      {/* <p> این متن صرفا برای تست فونت ها این پروژه است</p> */}
      <SharedUiDrawer menu={allowedMenuIds} />
    </div>
  );
}

export default DashboardFeatureShell;
